### ISSUE TITLE
Differences

### ISSUE THREAD

**Issue by ryker-s** [GorlotTechnologies/GorlotEngine#2]
What's the difference between this repo and nunu?

**Comment by Hermades** [comment]
I've been working in adding new things such as a lot of editor rewrite (by using nodes) and a blueprints-like system, a unity-like component system and in a future much more things that are written down in my ToDo's notebook <3. 

![Screenshot_2020-07-22_22-37-28](https://user-images.githubusercontent.com/63685134/88236217-058ecb80-cc6c-11ea-9edf-0209dc13a108.png)
![Screenshot_2020-07-22_22-37-55](https://user-images.githubusercontent.com/63685134/88236218-06276200-cc6c-11ea-8e90-f4d8dbc3287e.png)

Sorry for the late answer, because of a plethora of problems I hadn't time for exploring all my social networks.
